CREATE TABLE TBL_COMPANY_MEMBER(
                                   ID NUMBER CONSTRAINT PK_COMPANY_MEMBER PRIMARY KEY,
                                   COMPANY_ID NUMBER NOT NULL,
                                   COMPANY_MEMBER_POSITION VARCHAR2(1000) DEFAULT '사원',
                                   COMPANY_MEMBER_AUTHORITY VARCHAR2(1000) DEFAULT 'ADMIN',
                                   COMPANY_MEMBER_DEPARTMENT VARCHAR2(1000),
                                   CREATED_DATE DATE DEFAULT SYSDATE,
                                   UPDATED_DATE DATE DEFAULT SYSDATE,
                                   CONSTRAINT FK_COMPANY_MEMBER_COMPANY FOREIGN KEY(COMPANY_ID)
                                   REFERENCES TBL_COMPANY(ID),
                                   CONSTRAINT FK_COMPANY_MEMBER_MEMBER FOREIGN KEY(ID)
                                   REFERENCES TBL_MEMBER(ID)
);
<select id="selectMemberInfoAdmin" resultType="companyMemberInfoAdminDTO">
SELECT ID,  COMPANY_ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, YEAR, MONTH, COMPANY_EMPLOYEE,
       COMPANY_MAIN_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO ,COMPANY_MEMBER_DEPARTMENT, COMPANY_MEMBER_POSITION,
       MEMBER_RECENT_LOGIN, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_STATUS
FROM
    (
        SELECT ID, ROWNUM R, COMPANY_ID, COMPANY_NAME, COMPANY_BUSINESS_NUMBER, YEAR, MONTH,  COMPANY_EMPLOYEE,
               COMPANY_MAIN_ADDRESS, COMPANY_LOGO_PATH, COMPANY_URL, COMPANY_CERTIFICATE_PATH, COMPANY_INTRODUCE, COMPANY_WELFARE, COMPANY_CULTURE, COMPANY_CEO ,COMPANY_MEMBER_DEPARTMENT, COMPANY_MEMBER_POSITION,
               MEMBER_RECENT_LOGIN, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_STATUS
        FROM
            (
                SELECT M.ID, C.ID AS COMPANY_ID, C.COMPANY_NAME, C.COMPANY_BUSINESS_NUMBER, TO_CHAR(C.COMPANY_ESTABLISHMENT, 'YYYY') AS YEAR, TO_CHAR(C.COMPANY_ESTABLISHMENT, 'MM') AS MONTH,
                       C.COMPANY_EMPLOYEE, C.COMPANY_MAIN_ADDRESS, C.COMPANY_LOGO_PATH, C.COMPANY_URL, C.COMPANY_CERTIFICATE_PATH,               C.COMPANY_INTRODUCE, C.COMPANY_WELFARE, C.COMPANY_CULTURE, C.COMPANY_CEO ,CM.COMPANY_MEMBER_DEPARTMENT, CM.COMPANY_MEMBER_POSITION,
                       M.MEMBER_RECENT_LOGIN, M.MEMBER_NAME, M.MEMBER_PHONE, M.MEMBER_EMAIL, M.MEMBER_STATUS
                FROM TBL_COMPANY C
                         JOIN TBL_COMPANY_MEMBER CM
                              ON CM.COMPANY_ID = C.ID
                         JOIN TBL_MEMBER M
                              ON M.ID = CM.ID
                WHERE M.MEMBER_CLASS='기업'
                          <if test="status != 'all' and status != null">
                         AND M.MEMBER_STATUS = #{status}
                    </if>
                    <if test="keyword != null">
                    AND MEMBER_NAME LIKE '%' || #{keyword} || '%'
                    </if>
                        <if test="date != 0">
                         AND CEIL(SYSDATE - TO_DATE(M.MEMBER_RECENT_LOGIN)) <![CDATA[ <= #{date}]]>
                        </if>
                    ORDER BY M.ID DESC

                    )
        <![CDATA[
        WHERE ROWNUM <= ${endRow}
]]>
)
<![CDATA[
WHERE R >= ${startRow}
]]>
</select>

          <select id="selectAllMemberInfoAdmin" resultType="companyMemberInfoAdminDTO">
SELECT M.ID, C.ID AS COMPANY_ID, C.COMPANY_NAME, C.COMPANY_BUSINESS_NUMBER, TO_CHAR(C.COMPANY_ESTABLISHMENT, 'YYYY') YEAR, TO_CHAR(C.COMPANY_ESTABLISHMENT, 'MM') MONTH,
       CEIL((SYSDATE-TO_DATE(COMPANY_ESTABLISHMENT))/365) DURATION, C.COMPANY_EMPLOYEE, C.COMPANY_MAIN_ADDRESS, C.COMPANY_LOGO_PATH, C.COMPANY_URL, C.COMPANY_CERTIFICATE_PATH,               C.COMPANY_INTRODUCE, C.COMPANY_WELFARE, C.COMPANY_CULTURE, C.COMPANY_CEO ,CM.COMPANY_MEMBER_DEPARTMENT, CM.COMPANY_MEMBER_POSITION,
       M.MEMBER_RECENT_LOGIN, M.MEMBER_NAME, M.MEMBER_PHONE, M.MEMBER_EMAIL, M.MEMBER_STATUS
FROM TBL_COMPANY C
         JOIN TBL_COMPANY_MEMBER CM
              ON CM.COMPANY_ID = C.ID
         JOIN TBL_MEMBER M
              ON M.ID = CM.ID
WHERE M.MEMBER_CLASS='기업'
          </select>


SELECT DISTINCT M.MEMBER_NAME
FROM TBL_MEMBER M
JOIN TBL_COMPANY_MEMBER CM
ON M.ID = CM.ID
JOIN TBL_COMPANY C
ON C.ID = CM.COMPANY_ID
JOIN TBL_COMPANY_CATEGORY CC
ON C.ID = CC.COMPANY_ID;



