CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER
(
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_NAME          VARCHAR2(1000) NOT NULL,
    MEMBER_PHONE         VARCHAR2(1000),
    MEMBER_EMAIL         VARCHAR2(1000) NOT NULL,
    MEMBER_PASSWORD      VARCHAR2(1000),
    MEMBER_RECENT_LOGIN  DATE           DEFAULT SYSDATE,
    MEMBER_PROFILE_PATH  VARCHAR2(1000) DEFAULT '',
    MEMBER_CLASS         VARCHAR2(1000) DEFAULT '일반',
    MEMBER_POINT         NUMBER(10)     DEFAULT 0,
    MEMBER_STATUS        VARCHAR(1000)  DEFAULT '활성',
    CREATED_DATE         DATE           DEFAULT SYSDATE,
    UPDATED_DATE         DATE           DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;
ALTER TABLE TBL_MEMBER MODIFY MEMBER_PHONE VARCHAR2(1000) NULL;



SELECT CEIL(SYSDATE - TO_DATE(MEMBER_RECENT_LOGIN))
FROM TBL_MEMBER;


SELECT ID, MEMBER_NAME, MEMBER_EMAIL, CREATED_DATE, MEMBER_RECENT_LOGIN, MEMBER_STATUS         FROM TBL_MEMBER                                        ORDER BY ID DESC;


SELECT ID, MEMBER_NAME, MEMBER_EMAIL, TO_CHAR(CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE , TO_CHAR(MEMBER_RECENT_LOGIN, 'YYYY-MM-DD') AS MEMBER_RECENT_LOGIN, MEMBER_STATUS         FROM (         SELECT ID, ROWNUM R, MEMBER_NAME, MEMBER_EMAIL, CREATED_DATE, MEMBER_RECENT_LOGIN, MEMBER_STATUS         FROM         (         SELECT ID, MEMBER_NAME, MEMBER_EMAIL, CREATED_DATE, MEMBER_RECENT_LOGIN, MEMBER_STATUS         FROM TBL_MEMBER                                        ORDER BY ID DESC         )                   WHERE ROWNUM <= 10                   )                   WHERE R >= 0


SELECT COUNT(*)
FROM (
         SELECT ID, MEMBER_NAME, MEMBER_EMAIL, CREATED_DATE, MEMBER_RECENT_LOGIN, MEMBER_STATUS
         FROM TBL_MEMBER

         WHERE MEMBER_STATUS = '활성'
           AND MEMBER_NAME LIKE '%개인%'




            AND CEIL(SYSDATE - TO_DATE(MEMBER_RECENT_LOGIN)) <=

        );





SELECT *
FROM TBL_COMPANY_MEMBER CM
         JOIN TBL_MEMBER M
              ON CM.ID = M.ID
WHERE CM.ID IS NOT NULL AND M.MEMBER_STATUS = '활성' AND M.MEMBER_NAME LIKE '%한%' AND CEIL(SYSDATE - TO_DATE(M.MEMBER_RECENT_LOGIN)) < 100;


