SELECT CEIL(TO_DATE(PROGRAM_END_DATE)-SYSDATE)
FROM TBL_PROGRAM;

SELECT CEIL(SYSDATE - TO_DATE(CREATED_DATE))
FROM TBL_PROGRAM;

INSERT INTO TBL_PROGRAM (ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID, CREATED_DATE, UPDATED_DATE)
    (SELECT SEQ_PROGRAM.NEXTVAL, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID, SYSDATE, SYSDATE FROM TBL_PROGRAM);

SELECT *

FROM

                    (
                        SELECT P.ID, COMPANY_NAME, PROGRAM_NAME, P.CREATED_DATE, PROGRAM_END_DATE, P.PROGRAM_STATUS
                        FROM TBL_PROGRAM P
                                 JOIN TBL_COMPANY C
                                      ON P.COMPANY_ID = C.ID

                        WHERE P.PROGRAM_STATUS = '승인'  AND PROGRAM_NAME LIKE '%삼성%'AND CEIL(SYSDATE - TO_DATE(P.CREATED_DATE)) <=7

                        ORDER BY P.ID DESC
                    );





SELECT COUNT(*) AS TOTAL
FROM
    (
    SELECT ID, COMPANY_NAME, PROGRAM_NAME, TO_CHAR(CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE ,
           TO_CHAR(PROGRAM_END_DATE, 'YYYY-MM-DD') AS PROGRAM_END_DATE, PROGRAM_STATUS
    FROM
        (
        SELECT ID, ROWNUM R, COMPANY_NAME, PROGRAM_NAME, CREATED_DATE, PROGRAM_END_DATE, PROGRAM_STATUS
        FROM
            (
            SELECT P.ID, COMPANY_NAME, PROGRAM_NAME, P.CREATED_DATE, PROGRAM_END_DATE, P.PROGRAM_STATUS
            FROM TBL_PROGRAM P
                JOIN TBL_COMPANY C
                    ON P.COMPANY_ID = C.ID
            WHERE
                ORDER BY P.ID DESC
                )
        WHERE ROWNUM <= 0
        )
    WHERE R >= 0
    )