SELECT CEIL(TO_DATE(PROGRAM_END_DATE)-SYSDATE)
FROM TBL_PROGRAM;

SELECT CEIL(SYSDATE - TO_DATE(CREATED_DATE))
FROM TBL_PROGRAM;

INSERT INTO TBL_PROGRAM (ID, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID, CREATED_DATE, UPDATED_DATE)
    (SELECT SEQ_PROGRAM.NEXTVAL, PROGRAM_NAME, PROGRAM_DETAIL, PROGRAM_EXPIRED, PROGRAM_STATUS, PROGRAM_END_DATE, PROGRAM_PRICE, PROGRAM_BENEFIT, PROGRAM_THUMBNAIL_PATH, COMPANY_ID, CATEGORY_C_ID, SYSDATE, SYSDATE FROM TBL_PROGRAM);
